---
## Add binding to the above role
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: chimera-custom-resources-admin
  namespace: {{ template "namespace.fullname" . }}
subjects:
- kind: Group
  name: keycloak_group://{{ required "A valid .Values.keycloakBaseGroup entry required!" .Values.keycloakBaseGroup }}-admin
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: chimera-custom-resources-admin
  apiGroup: rbac.authorization.k8s.io
