# This hook depends on helm creating the target namespace if it doesn't exist
# before the hook is called. This is the case on Helm v2.9.1
apiVersion: batch/v1
kind: Job
metadata:
  name: label-ns-{{ template "namespace.fullname" . }}
  namespace: kube-system
  labels:
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  ttlSecondsAfterFinished: 100
  template:
    spec:
      containers:
      - name: labeler
        image: gcr.io/google_containers/hyperkube:v1.9.7
        command:
        - kubectl
        - label
        - ns
        - {{ template "namespace.fullname" . }}
        - sam-id={{ .Values.samId }}
        - org={{ .Values.contact.organization }}
        - group={{ .Values.contact.group }}
        - contact={{ .Values.contact.email | replace "@" "_at_" }}
        {{- if .Values.chimeraManaged }}
        - chimera-managed=true
        {{- end}}
        - tier={{ .Values.tier }}
        - --overwrite
      restartPolicy: Never
      serviceAccountName: namespace-labeler
