apiVersion: v1
kind: ResourceQuota
metadata:
  name: {{ template "namespace.fullname" . }}-base-quota
  namespace: {{ template "namespace.fullname" . }}
  labels:
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
spec:
  hard:
    {{- .Values.quota.hard | toYaml | trimSuffix "\n" | nindent 4 }}
---
apiVersion: v1
kind: LimitRange
metadata:
  name:  {{ template "namespace.fullname" . }}-limits
  namespace: {{ template "namespace.fullname" . }}
spec:
  limits:
  - default:
{{ .Values.quota.defaultLimit | toYaml | trimSuffix "\n" | indent 6 }}
    defaultRequest:
{{ .Values.quota.defaultRequest | toYaml | trimSuffix "\n" | indent 6 }}
    type: Container
