
---
## Add binding to the read-only Role for namespaced  resources.
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: namespace-read
  namespace: {{ template "namespace.fullname" . }}
subjects:
- kind: Group
  name: keycloak_group://{{ .Values.keycloakBaseGroup }}
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: chimera-read-only-role
  apiGroup: rbac.authorization.k8s.io

---
## Add binding to the cluster-read ClusterRole. Provides read-only access to some non-namespaced resources
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "namespace.fullname" . }}-cluster-read
subjects:
- kind: Group
  name: keycloak_group://{{ .Values.keycloakBaseGroup }}-admin
  apiGroup: rbac.authorization.k8s.io
- kind: Group
  name: keycloak_group://{{ .Values.keycloakBaseGroup }}
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: chimera-cluster-read-for-dashboard
  apiGroup: rbac.authorization.k8s.io
